<?php
declare(strict_types=1);

// StephenKing SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

StephenKingUtility::setRegistrar(function (StephenKingUtility $u): void {
    $u->clean = [StephenKingClean::class, 'call'];
    $u->done = [StephenKingDone::class, 'call'];
    $u->make_error = [StephenKingMakeError::class, 'call'];
    $u->feature_add = [StephenKingFeatureAdd::class, 'call'];
    $u->feature_hook = [StephenKingFeatureHook::class, 'call'];
    $u->feature_init = [StephenKingFeatureInit::class, 'call'];
    $u->fetcher = [StephenKingFetcher::class, 'call'];
    $u->make_fetch_def = [StephenKingMakeFetchDef::class, 'call'];
    $u->make_context = [StephenKingMakeContext::class, 'call'];
    $u->make_options = [StephenKingMakeOptions::class, 'call'];
    $u->make_request = [StephenKingMakeRequest::class, 'call'];
    $u->make_response = [StephenKingMakeResponse::class, 'call'];
    $u->make_result = [StephenKingMakeResult::class, 'call'];
    $u->make_point = [StephenKingMakePoint::class, 'call'];
    $u->make_spec = [StephenKingMakeSpec::class, 'call'];
    $u->make_url = [StephenKingMakeUrl::class, 'call'];
    $u->param = [StephenKingParam::class, 'call'];
    $u->prepare_auth = [StephenKingPrepareAuth::class, 'call'];
    $u->prepare_body = [StephenKingPrepareBody::class, 'call'];
    $u->prepare_headers = [StephenKingPrepareHeaders::class, 'call'];
    $u->prepare_method = [StephenKingPrepareMethod::class, 'call'];
    $u->prepare_params = [StephenKingPrepareParams::class, 'call'];
    $u->prepare_path = [StephenKingPreparePath::class, 'call'];
    $u->prepare_query = [StephenKingPrepareQuery::class, 'call'];
    $u->graphql_body = [StephenKingGraphql::class, 'body'];
    $u->graphql_errors = [StephenKingGraphql::class, 'errors'];
    $u->result_basic = [StephenKingResultBasic::class, 'call'];
    $u->result_body = [StephenKingResultBody::class, 'call'];
    $u->result_headers = [StephenKingResultHeaders::class, 'call'];
    $u->transform_request = [StephenKingTransformRequest::class, 'call'];
    $u->transform_response = [StephenKingTransformResponse::class, 'call'];
});
